<?php
require_once('Zend/Loader.php');
Zend_Loader::loadClass('Zend_Gdata_YouTube');
Zend_Loader::loadClass('Zend_Gdata_AuthSub');

if (!isset($_COOKIE['token'])) {
  if (isset($_GET['token'])) {
    $token = Zend_Gdata_AuthSub::getAuthSubSessionToken($_GET['token']);
    setcookie('token', $token, time() + 31536000, '/', 'fumusic.net'); } }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Youtube simple tool</title>
<link rel="stylesheet" type="text/css" href="form/view.css" media="all">
<script type="text/javascript" src="form/view.js"></script>

<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17727118-7']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

</head>
<body id="main_body">
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Video reupload</a></h1>
		<form id="form_340097" class="appnitro"  accept-charset="UTF-8" method="post" action="massdownup.php">
					<div class="form_description">
			<h2>Video reupload</h2>
			<p>Download video from YouTube, Vimeo, DailyMotion and others then upload to your YouTube account.</p>
		</div>						
			<ul >
<?php

function getAuthSubRequestUrl() {
    $next = 'http://www.fumusic.net/index.php';//pazi ovde na link
    $scope = 'http://uploads.gdata.youtube.com/';
    $secure = false;
    $session = true;
    return Zend_Gdata_AuthSub::getAuthSubTokenUri($next, $scope, $secure, $session); }
$auth_url = getAuthSubRequestUrl();

if (!isset($_COOKIE['token'])) {
  if (!isset($_GET['token'])) {
    echo "<p>First, please authorize application on YouTube ";
    echo "<input type=button value=Authorize onclick=\"javascript:window.location='$auth_url'\"/></p><br>"; } }
  


?>

<form method=post accept-charset="UTF-8" action=massdownup.php>
<input type=hidden name=token value=<?php if (isset($_COOKIE['token'])) echo $_COOKIE['token']; elseif (isset($token)) echo $token; else echo "";?>>
					<li id="li_1" >
		<label class="description" for="element_1">Video link </label>
		<div>
			<input id="element_1" name="links" class="element text large" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Title of new video </label>
		<div>
			<input id="element_2" name="title" class="element text large" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Description </label>
		<div>
			<textarea id="element_3" name="description" class="element textarea small"></textarea> 
		</div> 
		</li>		<li id="li_4" >
		<label class="description" for="element_4">Tags (separated by coma) </label>
		<div>
			<textarea id="element_4" name="tags" class="element textarea small"></textarea> 
		</div> 
		</li>		<li id="li_5" >
		<label class="description" for="element_5">Category </label>
		<div>
		<select class="element select medium" id="element_5" name="category"> 
			<option value="" selected="selected"></option>
<option value="Tech" >Tech</option>
<option value="Education" >Education</option>
<option value="Animals" >Animals</option>
<option value="People" >People</option>
<option value="Travel" >Travel</option>
<option value="Entertainment" >Entertainment</option>
<option value="Howto" >Howto</option>
<option value="Sports" >Sports</option>
<option value="Autos" >Autos</option>
<option value="Music" >Music</option>
<option value="News" >News</option>
<option value="Nonprofit" >Nonprofit</option>
<option value="Comedy" >Comedy</option>
<option value="Film" >Film</option>

		</select>
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="340097" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>

</body></html>
